version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.20.0
    working_directory: ~/repo

jobs:
  install-and-test:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Installer les dépendances
          command: npm install
      - run:
          name: Lancer les tests
          command: npm run test

workflows:
  test-and-deploy:
    jobs:
      - install-and-test
